### ISSUE TITLE
Implement score tracking

### ISSUE THREAD

**Issue by TheDutchCoder** [TheDutchCoder/atc-gjk#47]
- [x] Keep track of scores per plane exited
- [x] Keep track of scores per plane landed
- [x] Show total at the end
- [x] Game over at crash?
